using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using BehaviorTreeMainProject.Services;
using BehaviorTreeMainProject.Services.AIPlanning;
using BehaviorTreeMainProject.Services.FaultInjection;
using BehaviorTreeMainProject.ModelLoader;
using AIPlanning;
using BehaviorTreeMainProject.Log.Services;

namespace BehaviorTreeMainProject
{
    /// <summary>
    /// Initializes and runs a BehaviorTree from a JSON model file (generated by BTInstanceJsonGenerator)
    /// combined with a BehaviorTreeConfiguration for external settings.
    /// 
    /// This replaces hand-coded test files like DemonstratorTreeTest by reading the tree structure
    /// from the DSL-generated JSON and only requiring a configuration for planner paths, blackboard
    /// files, and runtime settings.
    /// </summary>
    public class BehaviorTreeRunner
    {
        private readonly BehaviorTreeConfiguration config;
        private readonly string jsonModelPath;
        private string faultConfigPath;
        private List<ServicePlanning> allPlanners = new();
        private DateTime testStartTime;
        private DateTime testEndTime;

        public BehaviorTreeRunner(string jsonModelPath, BehaviorTreeConfiguration config)
        {
            this.jsonModelPath = jsonModelPath ?? throw new ArgumentNullException(nameof(jsonModelPath));
            this.config = config ?? throw new ArgumentNullException(nameof(config));
        }

        /// <summary>Optional path to a fault-injection JSON config.</summary>
        public string FaultConfigPath
        {
            get => faultConfigPath;
            set => faultConfigPath = value;
        }

        /// <summary>
        /// Loads the JSON model, builds the behavior tree, and executes it.
        /// </summary>
        public async Task Run()
        {
            testStartTime = DateTime.Now;

            // 0. Pre-flight validation — fail fast with clear messages
            Validate();

            // 1. Load and parse JSON model
            var modelJson = LoadJsonModel(jsonModelPath);
            var treeJson = modelJson.GetProperty("behaviorTrees")[0];
            string treeName = treeJson.GetProperty("name").GetString();

            LoggingService.Initialize(treeName, enableConsole: true, enableFile: true);
            ExecutionFlowLogger.Initialize(treeName, enableConsole: true, enableFile: true);
            BTNode.EnableRemoteTickForwarding();

            LoggingService.LogSection($"BEHAVIOR TREE: {treeName}");
            LoggingService.LogSuccess($"Started at: {testStartTime:yyyy-MM-dd HH:mm:ss.fff}");
            EndToEndSummaryLogger.LogTaskStart(treeName);

            try
            {
                // 2. Create and populate blackboard
                using var blackboard = new Blackboard<FastName>();
                SetupBlackboard(blackboard);

                // 3. Build tree from JSON
                var behaviorTree = new BehaviorTree();
                behaviorTree.Initialise(blackboard, treeName);

                var rootJson = treeJson.GetProperty("root");
                BuildTreeFromJson(behaviorTree, rootJson, blackboard);

                // 3a. Attach fault injection service (if a fault config is available)
                AttachFaultInjectionService(behaviorTree, treeName);

                BlackboardSummaryLogger.CaptureBlackboardState(blackboard);

                // 4. Register ML subtree configuration
                RegisterSubtreeConfig();

                // 5. Display tree structure
                LogTreeStructure(behaviorTree, treeName);

                // 6. Execute
                LoggingService.LogSection($"EXECUTING {treeName}");
                await ExecuteTree(behaviorTree);

                // 7. Finalize
                testEndTime = DateTime.Now;
                LoggingService.LogSection($"{treeName} COMPLETED");
                LoggingService.LogSuccess($"Finished at: {testEndTime:yyyy-MM-dd HH:mm:ss.fff}");
                LoggingService.LogSuccess($"Total duration: {testEndTime - testStartTime:hh\\:mm\\:ss\\.fff}");
                EndToEndSummaryLogger.LogTaskEnd(true);

                await DisplayExecutionSummary();
                GenerateAllLogs(blackboard);
            }
            catch (Exception ex)
            {
                LoggingService.LogError($"ERROR during {treeName}: {ex.Message}");
                LoggingService.LogError($"   Stack trace: {ex.StackTrace}");
                LoggingService.GenerateSummaryTable();
                LoggingService.Close();
                ExecutionFlowLogger.Close();
                throw;
            }
        }

        // ── JSON loading ──

        private JsonElement LoadJsonModel(string path)
        {
            string fullPath = Path.GetFullPath(path);
            if (!File.Exists(fullPath))
                throw new FileNotFoundException($"BT model JSON not found: {fullPath}");

            string jsonText = File.ReadAllText(fullPath);
            using var doc = JsonDocument.Parse(jsonText);

            // Return a clone so the JsonDocument can be disposed
            return JsonSerializer.Deserialize<JsonElement>(doc.RootElement.GetRawText());
        }

        // ── Blackboard setup ──

        private void SetupBlackboard(Blackboard<FastName> blackboard)
        {
            var writer = new BlackboardWriter(blackboard);

            LoggingService.LogSection("REGISTERING ALL TYPES");
            writer.RegisterAllTypes();

            LoggingService.LogSection("REGISTERING ALL INSTANCES FROM FILES");
            writer.RegisterAllInstances(config.SetupObjectsFile, config.InitialStateFile, config.ActionInstancesFile);

            if (!string.IsNullOrEmpty(config.GoalStateFile))
            {
                writer.RegisterGoalStatePredicates(config.GoalStateFile);
            }
        }

        // ── Tree construction from JSON ──

        private void BuildTreeFromJson(BehaviorTree behaviorTree, JsonElement rootJson, Blackboard<FastName> blackboard)
        {
            LoggingService.LogSection("BUILDING BEHAVIOR TREE FROM JSON");

            var rootComposite = behaviorTree.root as BTFlowNodeComposite;

            // Read root nodeGraph
            var nodeGraph = rootJson.GetProperty("nodeGraph");
            var nodesArray = nodeGraph.GetProperty("nodes");
            int nodeCount = nodeGraph.GetProperty("nodeCount").GetInt32();

            // Disable global planning phase — each child plans and executes independently
            blackboard.PlanningPhase = false;
            blackboard.CassetteSubtreeCompleted = new bool[nodeCount];
            blackboard.SetBool(new FastName("ExecutionActive"), true);

            LoggingService.LogSection("CREATING FLOW NODES AND PLANNERS");

            int plannerIndex = 0;
            foreach (var nodeJson in nodesArray.EnumerateArray())
            {
                plannerIndex++;
                var flowNode = CreateFlowNodeFromJson(nodeJson, behaviorTree, plannerIndex);
                rootComposite.AddChild(flowNode);
            }

            LoggingService.LogSuccess($"Created {plannerIndex} flow nodes from JSON model");

            // Wire up the tree
            behaviorTree.root = rootComposite;
            rootComposite.SetOwiningTree(behaviorTree);
            rootComposite.SetTreeForAllServices(behaviorTree);

            // Store reference in blackboard
            blackboard.SetNodeGraph(new FastName("BehaviorTree"), new NodeGraph());
        }

        private DynamicFlowNode CreateFlowNodeFromJson(JsonElement nodeJson, BehaviorTree behaviorTree, int index)
        {
            string nodeName = nodeJson.GetProperty("name").GetString();
            string successCriteria = nodeJson.GetProperty("successCriteria").GetString();
            string childType = nodeJson.GetProperty("childType").GetString();

            var criteria = ParseSuccessCriteria(successCriteria);

            var flowNode = new DynamicFlowNode(
                new FastName(nodeName),
                behaviorTree,
                criteria,
                1.0f,
                false);

            // Extract planner info from services
            if (nodeJson.TryGetProperty("services", out var servicesJson))
            {
                foreach (var svcJson in servicesJson.EnumerateArray())
                {
                    string svcType = svcJson.GetProperty("type").GetString();
                    if (svcType == "ServicePDDLPlanning")
                    {
                        var planner = CreatePlannerFromJson(svcJson, behaviorTree);
                        flowNode.SetPlanningService(planner);
                        allPlanners.Add(planner);

                        string svcName = svcJson.GetProperty("name").GetString();
                        string domain = svcJson.TryGetProperty("domain", out var d) ? d.GetString() : "?";
                        string problem = svcJson.TryGetProperty("problem", out var p) ? p.GetString() : "?";
                        string plannerConfig = svcJson.TryGetProperty("config", out var c) ? c.GetString() : "default";

                        LoggingService.LogInfo($"  [{index,2}] {nodeName,-16}  planner={svcName}  domain={domain}  problem={problem}  config={plannerConfig}");
                    }
                }
            }

            return flowNode;
        }

        private ServicePDDLPlanning CreatePlannerFromJson(JsonElement serviceJson, BehaviorTree behaviorTree)
        {
            // Read planner details from the JSON
            string plannerType = serviceJson.TryGetProperty("plannerType", out var pt) ? pt.GetString() : "Enhsp";
            string enhspConfig = serviceJson.TryGetProperty("config", out var cfg) ? cfg.GetString() : null;

            // Read convention-resolved paths directly from JSON (set by the generator)
            string domainPath = serviceJson.TryGetProperty("domainPath", out var dp) ? dp.GetString() : null;
            string problemPath = serviceJson.TryGetProperty("problemPath", out var pp) ? pp.GetString() : null;

            if (domainPath == null)
            {
                string domainName = serviceJson.TryGetProperty("domain", out var dom) ? dom.GetString() : "Domain";
                LoggingService.LogWarning($"  No domainPath in JSON for {domainName}, falling back to convention");
                domainPath = $"./Plannerinputs/static/{domainName}.pddl";
            }

            // Let the Flask service resolve its own planner path when empty
            string plannerPath = "";

            var request = new PDDLPlanningRequest(
                domainPath,
                problemPath,
                plannerPath,
                plannerType)
            {
                TimeoutSeconds = config.TimeoutSeconds,
                MaxPlanLength = config.MaxPlanLength,
                EnhspConfig = enhspConfig
            };

            var planner = new ServicePDDLPlanning(behaviorTree, request);
            planner.ExecutionMode = config.GetExecutionMode();

            return planner;
        }

        // ── ML subtree registration ──

        private void RegisterSubtreeConfig()
        {
            if (string.IsNullOrEmpty(config.SubtreeDomainFile))
                return;

            var subtreeConfig = new ServiceSubtreeInject.SubtreeConfiguration(
                config.SubtreeConfigName, config.SubtreePlannerName, SuccessCriteria.ALL);

            subtreeConfig.PlannerParameters["domainFile"] = config.SubtreeDomainFile;
            subtreeConfig.PlannerParameters["problemFile"] = config.SubtreeProblemFile;
            subtreeConfig.PlannerParameters["plannerPath"] = "";  // Flask uses its own default
            subtreeConfig.PlannerParameters["timeoutSeconds"] = config.SubtreeTimeoutSeconds;
            subtreeConfig.PlannerParameters["maxPlanLength"] = config.SubtreeMaxPlanLength;
            subtreeConfig.PlannerParameters["executionMode"] = config.SubtreeExecutionMode switch
            {
                "Parallel" => ServicePDDLPlanning.ParallelExecutionMode.Parallel,
                "Hybrid" => ServicePDDLPlanning.ParallelExecutionMode.Hybrid,
                _ => ServicePDDLPlanning.ParallelExecutionMode.Sequential
            };
            subtreeConfig.PlannerParameters["enhspConfig"] = config.SubtreeEnhspConfig;

            ServiceSubtreeInject.RegisterGlobalConfiguration(config.SubtreeConfigName, subtreeConfig);
            ServiceSubtreeInject.DefaultSubtreeConfigName = config.SubtreeConfigName;

            LoggingService.LogSuccess($"Registered subtree config: {config.SubtreeConfigName}");
        }

        // ── Fault injection ──

        private void AttachFaultInjectionService(BehaviorTree behaviorTree, string treeName)
        {
            string path = faultConfigPath;
            if (string.IsNullOrEmpty(path))
            {
                // Convention: {TreeName}Faults.json next to the model JSON, then in workspace root
                string modelDir = Path.GetDirectoryName(Path.GetFullPath(jsonModelPath));
                string[] candidates =
                {
                    modelDir != null ? Path.Combine(modelDir, $"{treeName}Faults.json") : null,
                    Path.Combine(Directory.GetCurrentDirectory(), $"{treeName}Faults.json"),
                    Path.Combine(AppContext.BaseDirectory, $"{treeName}Faults.json"),
                };
                foreach (var c in candidates)
                {
                    if (!string.IsNullOrEmpty(c) && File.Exists(c))
                    {
                        path = c;
                        break;
                    }
                }
            }

            if (string.IsNullOrEmpty(path) || !File.Exists(path))
            {
                LoggingService.LogInfo("🧪 FaultInjection: No fault config discovered — skipping service attach");
                return;
            }

            var faultCfg = FaultInjectionConfig.LoadFromFile(path);
            if (faultCfg.Faults.Count == 0)
            {
                LoggingService.LogInfo("🧪 FaultInjection: Fault config is empty — skipping service attach");
                return;
            }

            var service = new FaultInjectionService(behaviorTree, faultCfg);
            behaviorTree.root.AddService(service, InIsAlwaysOn: true);
            LoggingService.LogSuccess($"🧪 FaultInjection: Attached service with {faultCfg.Faults.Count} fault(s) from {path}");
        }

        // ── Tree execution ──

        private async Task ExecuteTree(BehaviorTree behaviorTree)
        {
            int maxTicks = config.MaxTicks;
            int tickCount = 0;
            bool isPaused = false;

            LoggingService.LogInfo($"Starting tree execution (max {maxTicks} ticks)...");
            LoggingService.LogInfo("Controls: P = pause/resume, Q = quit");

            while (tickCount < maxTicks)
            {
                if (Console.KeyAvailable)
                {
                    var key = Console.ReadKey(true);
                    if (key.Key == ConsoleKey.Q)
                    {
                        LoggingService.LogWarning("Execution stopped by user (Q)");
                        break;
                    }
                    else if (key.Key == ConsoleKey.P)
                    {
                        isPaused = !isPaused;
                        if (isPaused)
                        {
                            EndToEndSummaryLogger.LogPauseStart();
                            var cmdHandler = new RuntimeCommandHandler(behaviorTree);
                            var cmdResult = cmdHandler.EnterCommandLoop();
                            isPaused = false;
                            EndToEndSummaryLogger.LogPauseEnd();
                            if (cmdResult == CommandResult.Quit)
                                return;
                            continue;
                        }
                        else
                            LoggingService.LogSuccess("RESUMED");
                    }
                }

                if (isPaused)
                {
                    await Task.Delay(200);
                    continue;
                }

                tickCount++;
                LoggingService.LogInfo($"\n--- TICK {tickCount} ---");

                BlackboardSummaryLogger.StartTreeTicking();
                var result = behaviorTree.Tick(0.1f);
                BlackboardSummaryLogger.EndTreeTicking();

                // Log flow node statuses
                var compositeRoot = behaviorTree.root as BTFlowNodeComposite;
                if (compositeRoot != null)
                {
                    var children = compositeRoot.GetChildren();
                    for (int i = 0; i < children.Count; i++)
                    {
                        if (children[i] is DynamicFlowNode dfn)
                        {
                            var graph = dfn.GetActionGraph();
                            var actionNodes = graph.GetAllActionNodes();
                            if (actionNodes.Count > 0)
                            {
                                LoggingService.LogInfo($"  {dfn.GetNodeName()}: {actionNodes.Count} actions in graph");
                            }
                        }
                    }
                }

                if (behaviorTree.HasFinished())
                {
                    LoggingService.LogSuccess($"Tree execution completed after {tickCount} ticks. Result: {result}");
                    break;
                }

                await Task.Delay(config.TickDelayMs);
            }

            if (tickCount >= maxTicks)
            {
                LoggingService.LogWarning($"Tree execution stopped after {maxTicks} ticks (max reached)");
            }
        }

        // ── Logging & summary ──

        private void LogTreeStructure(BehaviorTree behaviorTree, string treeName)
        {
            LoggingService.LogSection($"{treeName} TREE STRUCTURE");

            var rootComposite = behaviorTree.root as BTFlowNodeComposite;
            if (rootComposite == null) return;

            var children = rootComposite.GetChildren();
            LoggingService.LogInfo($"Root: BTFlowNodeComposite ({rootComposite.GetNodeName()})");
            LoggingService.LogInfo($"  |");

            for (int i = 0; i < children.Count; i++)
            {
                string connector = (i < children.Count - 1) ? "|-" : "\\-";
                if (children[i] is DynamicFlowNode dfn)
                {
                    string plannerInfo = dfn.ServicePlanning != null ? "PDDL" : "none";
                    LoggingService.LogInfo($"  {connector} DynamicFlowNode ({dfn.GetNodeName()}) [planner: {plannerInfo}]");
                }
            }
        }

        private async Task DisplayExecutionSummary()
        {
            LoggingService.LogSection("PLANNER EXECUTION SUMMARY");

            if (allPlanners.Count == 0)
            {
                LoggingService.LogWarning("No planners were executed.");
                return;
            }

            LoggingService.LogInfo($"Total planners: {allPlanners.Count}");
            var sortedPlanners = allPlanners.OrderBy(p => p.StartTime).ToList();

            for (int i = 0; i < sortedPlanners.Count; i++)
            {
                var planner = sortedPlanners[i];
                LoggingService.LogInfo($"  Planner {i + 1}: {planner.PlannerName}");
                LoggingService.LogInfo($"    Started: {planner.StartTime:HH:mm:ss.fff}");

                if (planner.HasCompleted)
                {
                    LoggingService.LogInfo($"    Finished: {planner.EndTime:HH:mm:ss.fff}");
                    LoggingService.LogInfo($"    Planner Duration: {planner.PlannerExecutionDuration:hh\\:mm\\:ss\\.fff}");
                    LoggingService.LogInfo($"    Total Duration: {planner.TotalExecutionDuration:hh\\:mm\\:ss\\.fff}");

                    if (planner.GeneratedNodeGraph != null)
                    {
                        LoggingService.LogInfo($"    Actions Generated: {planner.GeneratedNodeGraph.GetAllActionNodes().Count}");
                    }
                }
                else if (planner.IsExecuting)
                {
                    LoggingService.LogInfo($"    Still executing...");
                }
                else
                {
                    LoggingService.LogError($"    Failed or incomplete");
                }
            }

            var completed = allPlanners.Count(p => p.HasCompleted);
            var failed = allPlanners.Count(p => !p.HasCompleted && !p.IsExecuting);
            var executing = allPlanners.Count(p => p.IsExecuting);
            LoggingService.LogInfo($"  Completed: {completed}, Failed: {failed}, Executing: {executing}");
        }

        private void GenerateAllLogs(Blackboard<FastName> blackboard)
        {
            LoggingService.GenerateSummaryTable();
            BlackboardTrackingLogger.LogStatistics();
            BlackboardSummaryLogger.GenerateCSVSummary(blackboard);
            BlackboardSummaryLogger.Close();
            BehaviorTreeComponentLogger.GenerateCSVSummary(blackboard);
            BehaviorTreeComponentLogger.Close();
            TickTimingLogger.GenerateCSVSummary();
            TickTimingLogger.Close();
            PlannerCallLogger.GenerateCSVSummary();
            PlannerCallLogger.Close();
            ActionExecutionLogger.GenerateCSVSummary();
            ActionExecutionLogger.Instance.Close();
            RobotCommandLogger.GenerateCSVSummary();
            RobotCommandLogger.Close();
            HierarchicalTraceLogger.GenerateCSVSummary();
            HierarchicalTraceLogger.Close();
            EndToEndSummaryLogger.GenerateFinalSummary();
            EndToEndSummaryLogger.Close();
            LoggingService.Close();
            ExecutionFlowLogger.Close();
        }

        // ── Pre-flight validation ──

        /// <summary>
        /// Validates that the JSON model, blackboard files, and PDDL files all exist
        /// before starting the tick loop. Fails fast with a clear error listing all
        /// missing resources at once.
        /// </summary>
        private void Validate()
        {
            var missing = new List<string>();

            // Model JSON
            string fullModelPath = Path.GetFullPath(jsonModelPath);
            if (!File.Exists(fullModelPath))
                missing.Add($"Model JSON: {fullModelPath}");

            // Blackboard files
            CheckFile(config.SetupObjectsFile, "SetupObjectsFile", missing);
            CheckFile(config.InitialStateFile, "InitialStateFile", missing);
            CheckFile(config.ActionInstancesFile, "ActionInstancesFile", missing);
            if (!string.IsNullOrEmpty(config.GoalStateFile))
                CheckFile(config.GoalStateFile, "GoalStateFile", missing);

            // PDDL files referenced in the model JSON (check local copies)
            if (File.Exists(fullModelPath))
            {
                try
                {
                    string jsonText = File.ReadAllText(fullModelPath);
                    using var doc = JsonDocument.Parse(jsonText);
                    var trees = doc.RootElement.GetProperty("behaviorTrees");
                    foreach (var tree in trees.EnumerateArray())
                    {
                        var root = tree.GetProperty("root");
                        var nodes = root.GetProperty("nodeGraph").GetProperty("nodes");
                        foreach (var node in nodes.EnumerateArray())
                        {
                            if (!node.TryGetProperty("services", out var services)) continue;
                            foreach (var svc in services.EnumerateArray())
                            {
                                string svcType = svc.TryGetProperty("type", out var t) ? t.GetString() : "";
                                if (svcType != "ServicePDDLPlanning") continue;

                                string nodeName = node.TryGetProperty("name", out var n) ? n.GetString() : "?";

                                if (svc.TryGetProperty("domainPath", out var dp))
                                {
                                    string domPath = dp.GetString();
                                    string localDom = ResolveLocalPddlPath(domPath);
                                    if (localDom != null && !File.Exists(localDom))
                                        missing.Add($"PDDL domain ({nodeName}): {localDom}");
                                }

                                if (svc.TryGetProperty("problemPath", out var pp))
                                {
                                    string probPath = pp.GetString();
                                    string localProb = ResolveLocalPddlPath(probPath);
                                    if (localProb != null && !File.Exists(localProb))
                                        missing.Add($"PDDL problem ({nodeName}): {localProb}");
                                }
                            }
                        }
                    }
                }
                catch { /* validation is best-effort for PDDL paths */ }
            }

            if (missing.Count > 0)
            {
                string message = "Pre-flight validation failed. Missing files:\n  - " +
                    string.Join("\n  - ", missing);
                throw new FileNotFoundException(message);
            }
        }

        private static void CheckFile(string path, string label, List<string> missing)
        {
            if (string.IsNullOrEmpty(path))
            {
                missing.Add($"{label}: (not configured)");
                return;
            }
            string full = Path.GetFullPath(path);
            if (!File.Exists(full))
                missing.Add($"{label}: {full}");
        }

        /// <summary>
        /// Converts a convention PDDL path (e.g. ./Plannerinputs/static/Demonstrator/Domain.pddl)
        /// to a local file path relative to the python_service directory. Returns null if the
        /// path doesn't match the convention prefix.
        /// </summary>
        private static string ResolveLocalPddlPath(string conventionPath)
        {
            if (string.IsNullOrEmpty(conventionPath)) return null;

            // Strip leading "./" for resolution
            string clean = conventionPath.StartsWith("./") ? conventionPath.Substring(2) : conventionPath;

            if (clean.StartsWith("Plannerinputs/"))
            {
                string serviceDir = Path.Combine(
                    AppDomain.CurrentDomain.BaseDirectory, "..", "..", "..", "python_service");
                return Path.GetFullPath(Path.Combine(serviceDir, clean));
            }

            return null;
        }

        // ── Helpers ──

        private static SuccessCriteria ParseSuccessCriteria(string value)
        {
            return value?.ToUpperInvariant() switch
            {
                "ANY" => SuccessCriteria.ANY,
                "COUNT" => SuccessCriteria.COUNT,
                "PERCENTAGE" => SuccessCriteria.PERCENTAGE,
                _ => SuccessCriteria.ALL
            };
        }

        // ── Convenience entry point ──

        /// <summary>
        /// Runs a behavior tree from a JSON model file and an optional config file.
        /// Config resolution order:
        ///   1. Explicit configPath argument
        ///   2. Convention: {TreeName}Config.json next to the model JSON
        ///   3. Fallback: built-in defaults
        /// </summary>
        public static async Task RunFromFiles(string jsonModelPath, string configPath = null, string faultConfigPath = null)
        {
            BehaviorTreeConfiguration config;
            if (configPath != null && File.Exists(configPath))
            {
                config = BehaviorTreeConfiguration.LoadFromFile(configPath);
                Console.WriteLine($"[Config] Loaded from explicit path: {configPath}");
            }
            else
            {
                // Try convention: read tree name from JSON, look for {TreeName}Config.json
                string conventionPath = TryResolveConventionConfig(jsonModelPath);
                if (conventionPath != null && File.Exists(conventionPath))
                {
                    config = BehaviorTreeConfiguration.LoadFromFile(conventionPath);
                    Console.WriteLine($"[Config] Auto-discovered: {conventionPath}");
                }
                else
                {
                    config = BehaviorTreeConfiguration.CreateDemonstratorDefault();
                    Console.WriteLine("[Config] Using built-in defaults (no config file found)");
                }
            }

            var runner = new BehaviorTreeRunner(jsonModelPath, config);
            runner.FaultConfigPath = faultConfigPath;

            // Convention-resolve any missing blackboard file paths from the tree name
            ResolveConventionBlackboardPaths(runner.config, jsonModelPath);

            await runner.Run();
        }

        /// <summary>
        /// Fills in any missing blackboard file paths using naming convention:
        ///   {TreeName}SetupObjects.json, {TreeName}InitState.json,
        ///   {TreeName}GoalState.json in src/ModelLoader/
        ///   ActionInstances.txt in src/InputInstances/
        /// </summary>
        private static void ResolveConventionBlackboardPaths(BehaviorTreeConfiguration config, string jsonModelPath)
        {
            try
            {
                string fullPath = Path.GetFullPath(jsonModelPath);
                string jsonText = File.ReadAllText(fullPath);
                using var doc = JsonDocument.Parse(jsonText);
                string treeName = doc.RootElement
                    .GetProperty("behaviorTrees")[0]
                    .GetProperty("name")
                    .GetString();

                if (string.IsNullOrEmpty(treeName)) return;

                string srcBase = Path.Combine(
                    AppDomain.CurrentDomain.BaseDirectory, "..", "..", "..", "src");
                string modelLoaderDir = Path.Combine(srcBase, "ModelLoader");

                if (string.IsNullOrEmpty(config.SetupObjectsFile))
                {
                    string path = Path.Combine(modelLoaderDir, $"{treeName}SetupObjects.json");
                    if (File.Exists(path))
                    {
                        config.SetupObjectsFile = path;
                        Console.WriteLine($"[Convention] SetupObjects: {treeName}SetupObjects.json");
                    }
                }

                if (string.IsNullOrEmpty(config.InitialStateFile))
                {
                    string path = Path.Combine(modelLoaderDir, $"{treeName}InitState.json");
                    if (File.Exists(path))
                    {
                        config.InitialStateFile = path;
                        Console.WriteLine($"[Convention] InitialState: {treeName}InitState.json");
                    }
                }

                if (string.IsNullOrEmpty(config.GoalStateFile))
                {
                    string path = Path.Combine(modelLoaderDir, $"{treeName}GoalState.json");
                    if (File.Exists(path))
                    {
                        config.GoalStateFile = path;
                        Console.WriteLine($"[Convention] GoalState: {treeName}GoalState.json");
                    }
                }

                if (string.IsNullOrEmpty(config.ActionInstancesFile))
                {
                    string path = Path.Combine(srcBase, "InputInstances", "ActionInstances.txt");
                    if (File.Exists(path))
                    {
                        config.ActionInstancesFile = path;
                        Console.WriteLine($"[Convention] ActionInstances: ActionInstances.txt");
                    }
                }
            }
            catch { }
        }

        /// <summary>
        /// Reads the tree name from the JSON model and looks for {TreeName}Config.json
        /// in the same directory as the model file.
        /// </summary>
        private static string TryResolveConventionConfig(string jsonModelPath)
        {
            try
            {
                string fullPath = Path.GetFullPath(jsonModelPath);
                string dir = Path.GetDirectoryName(fullPath);
                string jsonText = File.ReadAllText(fullPath);
                using var doc = JsonDocument.Parse(jsonText);
                string treeName = doc.RootElement
                    .GetProperty("behaviorTrees")[0]
                    .GetProperty("name")
                    .GetString();

                if (!string.IsNullOrEmpty(treeName))
                    return Path.Combine(dir, $"{treeName}Config.json");
            }
            catch { }
            return null;
        }
    }
}
