(define (problem demonstrator-all-layers)
  (:domain trusshl)

  (:init
    ;; ===== BelongsToLayer =====
    ;; Table
    (belongstolayer table1 layer0)

    ;; Layer 1
    (belongstolayer stick1 layer1)
    (belongstolayer stick2 layer1)
    (belongstolayer stick3 layer1)
    (belongstolayer stick4 layer1)
    (belongstolayer stick5 layer1)

    ;; Layer 2
    (belongstolayer stick6 layer2)
    (belongstolayer stick7 layer2)
    (belongstolayer stick8 layer2)
    (belongstolayer stick9 layer2)
    (belongstolayer cube1 layer2)
    (belongstolayer cube2 layer2)

    ;; Layer 3
    (belongstolayer stick10 layer3)
    (belongstolayer stick11 layer3)
    (belongstolayer stick12 layer3)
    (belongstolayer stick13 layer3)
    (belongstolayer stick14 layer3)

    ;; Layer 4
    (belongstolayer stick15 layer4)
    (belongstolayer stick16 layer4)
    (belongstolayer stick17 layer4)
    (belongstolayer stick18 layer4)
    (belongstolayer cube3 layer4)
    (belongstolayer cube4 layer4)

    ;; Layer 5
    (belongstolayer stick19 layer5)
    (belongstolayer stick20 layer5)
    (belongstolayer stick21 layer5)
    (belongstolayer stick22 layer5)
    (belongstolayer stick23 layer5)

    ;; Layer 6
    (belongstolayer stick24 layer6)
    (belongstolayer stick25 layer6)
    (belongstolayer stick26 layer6)
    (belongstolayer stick27 layer6)
    (belongstolayer cube5 layer6)
    (belongstolayer cube6 layer6)

    ;; Layer 7
    (belongstolayer stick28 layer7)
    (belongstolayer stick29 layer7)
    (belongstolayer stick30 layer7)
    (belongstolayer stick31 layer7)
    (belongstolayer stick32 layer7)

    ;; Layer 8
    (belongstolayer stick33 layer8)
    (belongstolayer stick34 layer8)
    (belongstolayer stick35 layer8)
    (belongstolayer stick36 layer8)
    (belongstolayer cube7 layer8)
    (belongstolayer cube8 layer8)

    ;; Layer 9
    (belongstolayer stick37 layer9)
    (belongstolayer stick38 layer9)
    (belongstolayer stick39 layer9)
    (belongstolayer stick40 layer9)
    (belongstolayer stick41 layer9)

    ;; Layer 10
    (belongstolayer stick42 layer10)
    (belongstolayer stick43 layer10)
    (belongstolayer stick44 layer10)
    (belongstolayer stick45 layer10)
    (belongstolayer cube9 layer10)
    (belongstolayer cube10 layer10)

    ;; Layer 11
    (belongstolayer stick46 layer11)
    (belongstolayer stick47 layer11)
    (belongstolayer stick48 layer11)
    (belongstolayer stick49 layer11)
    (belongstolayer stick50 layer11)

    ;; Layer 12
    (belongstolayer stick51 layer12)
    (belongstolayer stick52 layer12)
    (belongstolayer stick53 layer12)
    (belongstolayer stick54 layer12)
    (belongstolayer cube11 layer12)
    (belongstolayer cube12 layer12)

    ;; Layer 13
    (belongstolayer stick55 layer13)
    (belongstolayer stick56 layer13)
    (belongstolayer stick57 layer13)
    (belongstolayer stick58 layer13)
    (belongstolayer stick59 layer13)

    ;; Layer 14
    (belongstolayer stick60 layer14)
    (belongstolayer stick61 layer14)
    (belongstolayer stick62 layer14)
    (belongstolayer stick63 layer14)
    (belongstolayer cube13 layer14)
    (belongstolayer cube14 layer14)

    ;; Layer 15
    (belongstolayer stick64 layer15)
    (belongstolayer stick65 layer15)
    (belongstolayer stick66 layer15)
    (belongstolayer stick67 layer15)
    (belongstolayer stick68 layer15)

    ;; Layer 16
    (belongstolayer stick69 layer16)
    (belongstolayer stick70 layer16)
    (belongstolayer stick71 layer16)
    (belongstolayer stick72 layer16)
    (belongstolayer cube15 layer16)

    ;; Layer 17
    (belongstolayer stick73 layer17)
    (belongstolayer stick74 layer17)
    (belongstolayer stick75 layer17)
    (belongstolayer stick76 layer17)

    ;; Layer 18
    (belongstolayer stick77 layer18)
    (belongstolayer stick78 layer18)
    (belongstolayer stick79 layer18)
    (belongstolayer cube16 layer18)

    ;; Layer 19
    (belongstolayer stick80 layer19)
    (belongstolayer stick81 layer19)
    (belongstolayer stick82 layer19)

    ;; Layer 20
    (belongstolayer stick83 layer20)
    (belongstolayer stick84 layer20)
    (belongstolayer cube17 layer20)

    ;; Layer 21
    (belongstolayer stick85 layer21)
    (belongstolayer stick86 layer21)

    ;; Layer 22
    (belongstolayer stick87 layer22)
    (belongstolayer cube18 layer22)

    ;; Layer 23
    (belongstolayer stick88 layer23)

    ;; ===== Clear =====
    (clear stick1)
    (clear stick2)
    (clear stick3)
    (clear stick4)
    (clear stick5)
    (clear stick6)
    (clear stick7)
    (clear stick8)
    (clear stick9)
    (clear stick10)
    (clear stick11)
    (clear stick12)
    (clear stick13)
    (clear stick14)
    (clear stick15)
    (clear stick16)
    (clear stick17)
    (clear stick18)
    (clear stick19)
    (clear stick20)
    (clear stick21)
    (clear stick22)
    (clear stick23)
    (clear stick24)
    (clear stick25)
    (clear stick26)
    (clear stick27)
    (clear stick28)
    (clear stick29)
    (clear stick30)
    (clear stick31)
    (clear stick32)
    (clear stick33)
    (clear stick34)
    (clear stick35)
    (clear stick36)
    (clear stick37)
    (clear stick38)
    (clear stick39)
    (clear stick40)
    (clear stick41)
    (clear stick42)
    (clear stick43)
    (clear stick44)
    (clear stick45)
    (clear stick46)
    (clear stick47)
    (clear stick48)
    (clear stick49)
    (clear stick50)
    (clear stick51)
    (clear stick52)
    (clear stick53)
    (clear stick54)
    (clear stick55)
    (clear stick56)
    (clear stick57)
    (clear stick58)
    (clear stick59)
    (clear stick60)
    (clear stick61)
    (clear stick62)
    (clear stick63)
    (clear stick64)
    (clear stick65)
    (clear stick66)
    (clear stick67)
    (clear stick68)
    (clear stick69)
    (clear stick70)
    (clear stick71)
    (clear stick72)
    (clear stick73)
    (clear stick74)
    (clear stick75)
    (clear stick76)
    (clear stick77)
    (clear stick78)
    (clear stick79)
    (clear stick80)
    (clear stick81)
    (clear stick82)
    (clear stick83)
    (clear stick84)
    (clear stick85)
    (clear stick86)
    (clear stick87)
    (clear stick88)
    (clear cube1)
    (clear cube2)
    (clear cube3)
    (clear cube4)
    (clear cube5)
    (clear cube6)
    (clear cube7)
    (clear cube8)
    (clear cube9)
    (clear cube10)
    (clear cube11)
    (clear cube12)
    (clear cube13)
    (clear cube14)
    (clear cube15)
    (clear cube16)
    (clear cube17)
    (clear cube18)

    ;; ===== AtPlace (all elements at initial locations) =====
    (atplace stick1 initlocstick1)
    (atplace stick2 initlocstick2)
    (atplace stick3 initlocstick3)
    (atplace stick4 initlocstick4)
    (atplace stick5 initlocstick5)
    (atplace stick6 initlocstick6)
    (atplace stick7 initlocstick7)
    (atplace stick8 initlocstick8)
    (atplace stick9 initlocstick9)
    (atplace stick10 initlocstick10)
    (atplace stick11 initlocstick11)
    (atplace stick12 initlocstick12)
    (atplace stick13 initlocstick13)
    (atplace stick14 initlocstick14)
    (atplace stick15 initlocstick15)
    (atplace stick16 initlocstick16)
    (atplace stick17 initlocstick17)
    (atplace stick18 initlocstick18)
    (atplace stick19 initlocstick19)
    (atplace stick20 initlocstick20)
    (atplace stick21 initlocstick21)
    (atplace stick22 initlocstick22)
    (atplace stick23 initlocstick23)
    (atplace stick24 initlocstick24)
    (atplace stick25 initlocstick25)
    (atplace stick26 initlocstick26)
    (atplace stick27 initlocstick27)
    (atplace stick28 initlocstick28)
    (atplace stick29 initlocstick29)
    (atplace stick30 initlocstick30)
    (atplace stick31 initlocstick31)
    (atplace stick32 initlocstick32)
    (atplace stick33 initlocstick33)
    (atplace stick34 initlocstick34)
    (atplace stick35 initlocstick35)
    (atplace stick36 initlocstick36)
    (atplace stick37 initlocstick37)
    (atplace stick38 initlocstick38)
    (atplace stick39 initlocstick39)
    (atplace stick40 initlocstick40)
    (atplace stick41 initlocstick41)
    (atplace stick42 initlocstick42)
    (atplace stick43 initlocstick43)
    (atplace stick44 initlocstick44)
    (atplace stick45 initlocstick45)
    (atplace stick46 initlocstick46)
    (atplace stick47 initlocstick47)
    (atplace stick48 initlocstick48)
    (atplace stick49 initlocstick49)
    (atplace stick50 initlocstick50)
    (atplace stick51 initlocstick51)
    (atplace stick52 initlocstick52)
    (atplace stick53 initlocstick53)
    (atplace stick54 initlocstick54)
    (atplace stick55 initlocstick55)
    (atplace stick56 initlocstick56)
    (atplace stick57 initlocstick57)
    (atplace stick58 initlocstick58)
    (atplace stick59 initlocstick59)
    (atplace stick60 initlocstick60)
    (atplace stick61 initlocstick61)
    (atplace stick62 initlocstick62)
    (atplace stick63 initlocstick63)
    (atplace stick64 initlocstick64)
    (atplace stick65 initlocstick65)
    (atplace stick66 initlocstick66)
    (atplace stick67 initlocstick67)
    (atplace stick68 initlocstick68)
    (atplace stick69 initlocstick69)
    (atplace stick70 initlocstick70)
    (atplace stick71 initlocstick71)
    (atplace stick72 initlocstick72)
    (atplace stick73 initlocstick73)
    (atplace stick74 initlocstick74)
    (atplace stick75 initlocstick75)
    (atplace stick76 initlocstick76)
    (atplace stick77 initlocstick77)
    (atplace stick78 initlocstick78)
    (atplace stick79 initlocstick79)
    (atplace stick80 initlocstick80)
    (atplace stick81 initlocstick81)
    (atplace stick82 initlocstick82)
    (atplace stick83 initlocstick83)
    (atplace stick84 initlocstick84)
    (atplace stick85 initlocstick85)
    (atplace stick86 initlocstick86)
    (atplace stick87 initlocstick87)
    (atplace stick88 initlocstick88)
    (atplace cube1 initloccube1)
    (atplace cube2 initloccube2)
    (atplace cube3 initloccube3)
    (atplace cube4 initloccube4)
    (atplace cube5 initloccube5)
    (atplace cube6 initloccube6)
    (atplace cube7 initloccube7)
    (atplace cube8 initloccube8)
    (atplace cube9 initloccube9)
    (atplace cube10 initloccube10)
    (atplace cube11 initloccube11)
    (atplace cube12 initloccube12)
    (atplace cube13 initloccube13)
    (atplace cube14 initloccube14)
    (atplace cube15 initloccube15)
    (atplace cube16 initloccube16)
    (atplace cube17 initloccube17)
    (atplace cube18 initloccube18)

    ;; ===== GripperEmpty & HasTool =====
    (gripperempty robot1)
    (hastool robot1 gripper1)

    ;; ===== ObjectFinalPosition =====
    (objectfinalposition stick1 finallocstick1)
    (objectfinalposition stick2 finallocstick2)
    (objectfinalposition stick3 finallocstick3)
    (objectfinalposition stick4 finallocstick4)
    (objectfinalposition stick5 finallocstick5)
    (objectfinalposition stick6 finallocstick6)
    (objectfinalposition stick7 finallocstick7)
    (objectfinalposition stick8 finallocstick8)
    (objectfinalposition stick9 finallocstick9)
    (objectfinalposition cube1 finloccube1)
    (objectfinalposition cube2 finloccube2)
    (objectfinalposition stick10 finallocstick10)
    (objectfinalposition stick11 finallocstick11)
    (objectfinalposition stick12 finallocstick12)
    (objectfinalposition stick13 finallocstick13)
    (objectfinalposition stick14 finallocstick14)
    (objectfinalposition stick15 finallocstick15)
    (objectfinalposition stick16 finallocstick16)
    (objectfinalposition stick17 finallocstick17)
    (objectfinalposition stick18 finallocstick18)
    (objectfinalposition cube3 finloccube3)
    (objectfinalposition cube4 finloccube4)
    (objectfinalposition stick19 finallocstick19)
    (objectfinalposition stick20 finallocstick20)
    (objectfinalposition stick21 finallocstick21)
    (objectfinalposition stick22 finallocstick22)
    (objectfinalposition stick23 finallocstick23)
    (objectfinalposition stick24 finallocstick24)
    (objectfinalposition stick25 finallocstick25)
    (objectfinalposition stick26 finallocstick26)
    (objectfinalposition stick27 finallocstick27)
    (objectfinalposition cube5 finloccube5)
    (objectfinalposition cube6 finloccube6)
    (objectfinalposition stick28 finallocstick28)
    (objectfinalposition stick29 finallocstick29)
    (objectfinalposition stick30 finallocstick30)
    (objectfinalposition stick31 finallocstick31)
    (objectfinalposition stick32 finallocstick32)
    (objectfinalposition stick33 finallocstick33)
    (objectfinalposition stick34 finallocstick34)
    (objectfinalposition stick35 finallocstick35)
    (objectfinalposition stick36 finallocstick36)
    (objectfinalposition cube7 finloccube7)
    (objectfinalposition cube8 finloccube8)
    (objectfinalposition stick37 finallocstick37)
    (objectfinalposition stick38 finallocstick38)
    (objectfinalposition stick39 finallocstick39)
    (objectfinalposition stick40 finallocstick40)
    (objectfinalposition stick41 finallocstick41)
    (objectfinalposition stick42 finallocstick42)
    (objectfinalposition stick43 finallocstick43)
    (objectfinalposition stick44 finallocstick44)
    (objectfinalposition stick45 finallocstick45)
    (objectfinalposition cube9 finloccube9)
    (objectfinalposition cube10 finloccube10)
    (objectfinalposition stick46 finallocstick46)
    (objectfinalposition stick47 finallocstick47)
    (objectfinalposition stick48 finallocstick48)
    (objectfinalposition stick49 finallocstick49)
    (objectfinalposition stick50 finallocstick50)
    (objectfinalposition stick51 finallocstick51)
    (objectfinalposition stick52 finallocstick52)
    (objectfinalposition stick53 finallocstick53)
    (objectfinalposition stick54 finallocstick54)
    (objectfinalposition cube11 finloccube11)
    (objectfinalposition cube12 finloccube12)
    (objectfinalposition stick55 finallocstick55)
    (objectfinalposition stick56 finallocstick56)
    (objectfinalposition stick57 finallocstick57)
    (objectfinalposition stick58 finallocstick58)
    (objectfinalposition stick59 finallocstick59)
    (objectfinalposition stick60 finallocstick60)
    (objectfinalposition stick61 finallocstick61)
    (objectfinalposition stick62 finallocstick62)
    (objectfinalposition stick63 finallocstick63)
    (objectfinalposition cube13 finloccube13)
    (objectfinalposition cube14 finloccube14)
    (objectfinalposition stick64 finallocstick64)
    (objectfinalposition stick65 finallocstick65)
    (objectfinalposition stick66 finallocstick66)
    (objectfinalposition stick67 finallocstick67)
    (objectfinalposition stick68 finallocstick68)
    (objectfinalposition stick69 finallocstick69)
    (objectfinalposition stick70 finallocstick70)
    (objectfinalposition stick71 finallocstick71)
    (objectfinalposition stick72 finallocstick72)
    (objectfinalposition cube15 finloccube15)
    (objectfinalposition stick73 finallocstick73)
    (objectfinalposition stick74 finallocstick74)
    (objectfinalposition stick75 finallocstick75)
    (objectfinalposition stick76 finallocstick76)
    (objectfinalposition stick77 finallocstick77)
    (objectfinalposition stick78 finallocstick78)
    (objectfinalposition stick79 finallocstick79)
    (objectfinalposition cube16 finloccube16)
    (objectfinalposition stick80 finallocstick80)
    (objectfinalposition stick81 finallocstick81)
    (objectfinalposition stick82 finallocstick82)
    (objectfinalposition stick83 finallocstick83)
    (objectfinalposition stick84 finallocstick84)
    (objectfinalposition cube17 finloccube17)
    (objectfinalposition stick85 finallocstick85)
    (objectfinalposition stick86 finallocstick86)
    (objectfinalposition stick87 finallocstick87)
    (objectfinalposition cube18 finloccube18)
    (objectfinalposition stick88 finallocstick88)

    ;; ===== Table =====
    (fixed table1)
    (atfinalposition table1)
    (atplace table1 mp5)
    (accessible table1)
  )
)
