(define (problem demonstrator-all-layers)
  (:domain trusshl)
  (:objects
    ;; Elements - Sticks (stick1 through stick88)
    stick1 - stick
    stick2 - stick
    stick3 - stick
    stick4 - stick
    stick5 - stick
    stick6 - stick
    stick7 - stick
    stick8 - stick
    stick9 - stick
    stick10 - stick
    stick11 - stick
    stick12 - stick
    stick13 - stick
    stick14 - stick
    stick15 - stick
    stick16 - stick
    stick17 - stick
    stick18 - stick
    stick19 - stick
    stick20 - stick
    stick21 - stick
    stick22 - stick
    stick23 - stick
    stick24 - stick
    stick25 - stick
    stick26 - stick
    stick27 - stick
    stick28 - stick
    stick29 - stick
    stick30 - stick
    stick31 - stick
    stick32 - stick
    stick33 - stick
    stick34 - stick
    stick35 - stick
    stick36 - stick
    stick37 - stick
    stick38 - stick
    stick39 - stick
    stick40 - stick
    stick41 - stick
    stick42 - stick
    stick43 - stick
    stick44 - stick
    stick45 - stick
    stick46 - stick
    stick47 - stick
    stick48 - stick
    stick49 - stick
    stick50 - stick
    stick51 - stick
    stick52 - stick
    stick53 - stick
    stick54 - stick
    stick55 - stick
    stick56 - stick
    stick57 - stick
    stick58 - stick
    stick59 - stick
    stick60 - stick
    stick61 - stick
    stick62 - stick
    stick63 - stick
    stick64 - stick
    stick65 - stick
    stick66 - stick
    stick67 - stick
    stick68 - stick
    stick69 - stick
    stick70 - stick
    stick71 - stick
    stick72 - stick
    stick73 - stick
    stick74 - stick
    stick75 - stick
    stick76 - stick
    stick77 - stick
    stick78 - stick
    stick79 - stick
    stick80 - stick
    stick81 - stick
    stick82 - stick
    stick83 - stick
    stick84 - stick
    stick85 - stick
    stick86 - stick
    stick87 - stick
    stick88 - stick

    ;; Elements - Cubes (cube1 through cube18)
    cube1 - cube
    cube2 - cube
    cube3 - cube
    cube4 - cube
    cube5 - cube
    cube6 - cube
    cube7 - cube
    cube8 - cube
    cube9 - cube
    cube10 - cube
    cube11 - cube
    cube12 - cube
    cube13 - cube
    cube14 - cube
    cube15 - cube
    cube16 - cube
    cube17 - cube
    cube18 - cube

    ;; Table
    table1 - table

    ;; Layers (layer0 through layer23)
    layer0 - stack
    layer1 - stack
    layer2 - stack
    layer3 - stack
    layer4 - stack
    layer5 - stack
    layer6 - stack
    layer7 - stack
    layer8 - stack
    layer9 - stack
    layer10 - stack
    layer11 - stack
    layer12 - stack
    layer13 - stack
    layer14 - stack
    layer15 - stack
    layer16 - stack
    layer17 - stack
    layer18 - stack
    layer19 - stack
    layer20 - stack
    layer21 - stack
    layer22 - stack
    layer23 - stack

    ;; Agent
    robot1 - robot

    ;; Tools
    gripper1 - gripper
    staplergun1 - staplergun

    ;; Locations - Initial (first positions)
    initlocstick1 - firstposition
    initlocstick2 - firstposition
    initlocstick3 - firstposition
    initlocstick4 - firstposition
    initlocstick5 - firstposition
    initlocstick6 - firstposition
    initlocstick7 - firstposition
    initlocstick8 - firstposition
    initlocstick9 - firstposition
    initlocstick10 - firstposition
    initlocstick11 - firstposition
    initlocstick12 - firstposition
    initlocstick13 - firstposition
    initlocstick14 - firstposition
    initlocstick15 - firstposition
    initlocstick16 - firstposition
    initlocstick17 - firstposition
    initlocstick18 - firstposition
    initlocstick19 - firstposition
    initlocstick20 - firstposition
    initlocstick21 - firstposition
    initlocstick22 - firstposition
    initlocstick23 - firstposition
    initlocstick24 - firstposition
    initlocstick25 - firstposition
    initlocstick26 - firstposition
    initlocstick27 - firstposition
    initlocstick28 - firstposition
    initlocstick29 - firstposition
    initlocstick30 - firstposition
    initlocstick31 - firstposition
    initlocstick32 - firstposition
    initlocstick33 - firstposition
    initlocstick34 - firstposition
    initlocstick35 - firstposition
    initlocstick36 - firstposition
    initlocstick37 - firstposition
    initlocstick38 - firstposition
    initlocstick39 - firstposition
    initlocstick40 - firstposition
    initlocstick41 - firstposition
    initlocstick42 - firstposition
    initlocstick43 - firstposition
    initlocstick44 - firstposition
    initlocstick45 - firstposition
    initlocstick46 - firstposition
    initlocstick47 - firstposition
    initlocstick48 - firstposition
    initlocstick49 - firstposition
    initlocstick50 - firstposition
    initlocstick51 - firstposition
    initlocstick52 - firstposition
    initlocstick53 - firstposition
    initlocstick54 - firstposition
    initlocstick55 - firstposition
    initlocstick56 - firstposition
    initlocstick57 - firstposition
    initlocstick58 - firstposition
    initlocstick59 - firstposition
    initlocstick60 - firstposition
    initlocstick61 - firstposition
    initlocstick62 - firstposition
    initlocstick63 - firstposition
    initlocstick64 - firstposition
    initlocstick65 - firstposition
    initlocstick66 - firstposition
    initlocstick67 - firstposition
    initlocstick68 - firstposition
    initlocstick69 - firstposition
    initlocstick70 - firstposition
    initlocstick71 - firstposition
    initlocstick72 - firstposition
    initlocstick73 - firstposition
    initlocstick74 - firstposition
    initlocstick75 - firstposition
    initlocstick76 - firstposition
    initlocstick77 - firstposition
    initlocstick78 - firstposition
    initlocstick79 - firstposition
    initlocstick80 - firstposition
    initlocstick81 - firstposition
    initlocstick82 - firstposition
    initlocstick83 - firstposition
    initlocstick84 - firstposition
    initlocstick85 - firstposition
    initlocstick86 - firstposition
    initlocstick87 - firstposition
    initlocstick88 - firstposition
    initloccube1 - firstposition
    initloccube2 - firstposition
    initloccube3 - firstposition
    initloccube4 - firstposition
    initloccube5 - firstposition
    initloccube6 - firstposition
    initloccube7 - firstposition
    initloccube8 - firstposition
    initloccube9 - firstposition
    initloccube10 - firstposition
    initloccube11 - firstposition
    initloccube12 - firstposition
    initloccube13 - firstposition
    initloccube14 - firstposition
    initloccube15 - firstposition
    initloccube16 - firstposition
    initloccube17 - firstposition
    initloccube18 - firstposition

    ;; Locations - Final positions
    mp5 - finalposition
    finallocstick1 - finalposition
    finallocstick2 - finalposition
    finallocstick3 - finalposition
    finallocstick4 - finalposition
    finallocstick5 - finalposition
    finallocstick6 - finalposition
    finallocstick7 - finalposition
    finallocstick8 - finalposition
    finallocstick9 - finalposition
    finallocstick10 - finalposition
    finallocstick11 - finalposition
    finallocstick12 - finalposition
    finallocstick13 - finalposition
    finallocstick14 - finalposition
    finallocstick15 - finalposition
    finallocstick16 - finalposition
    finallocstick17 - finalposition
    finallocstick18 - finalposition
    finallocstick19 - finalposition
    finallocstick20 - finalposition
    finallocstick21 - finalposition
    finallocstick22 - finalposition
    finallocstick23 - finalposition
    finallocstick24 - finalposition
    finallocstick25 - finalposition
    finallocstick26 - finalposition
    finallocstick27 - finalposition
    finallocstick28 - finalposition
    finallocstick29 - finalposition
    finallocstick30 - finalposition
    finallocstick31 - finalposition
    finallocstick32 - finalposition
    finallocstick33 - finalposition
    finallocstick34 - finalposition
    finallocstick35 - finalposition
    finallocstick36 - finalposition
    finallocstick37 - finalposition
    finallocstick38 - finalposition
    finallocstick39 - finalposition
    finallocstick40 - finalposition
    finallocstick41 - finalposition
    finallocstick42 - finalposition
    finallocstick43 - finalposition
    finallocstick44 - finalposition
    finallocstick45 - finalposition
    finallocstick46 - finalposition
    finallocstick47 - finalposition
    finallocstick48 - finalposition
    finallocstick49 - finalposition
    finallocstick50 - finalposition
    finallocstick51 - finalposition
    finallocstick52 - finalposition
    finallocstick53 - finalposition
    finallocstick54 - finalposition
    finallocstick55 - finalposition
    finallocstick56 - finalposition
    finallocstick57 - finalposition
    finallocstick58 - finalposition
    finallocstick59 - finalposition
    finallocstick60 - finalposition
    finallocstick61 - finalposition
    finallocstick62 - finalposition
    finallocstick63 - finalposition
    finallocstick64 - finalposition
    finallocstick65 - finalposition
    finallocstick66 - finalposition
    finallocstick67 - finalposition
    finallocstick68 - finalposition
    finallocstick69 - finalposition
    finallocstick70 - finalposition
    finallocstick71 - finalposition
    finallocstick72 - finalposition
    finallocstick73 - finalposition
    finallocstick74 - finalposition
    finallocstick75 - finalposition
    finallocstick76 - finalposition
    finallocstick77 - finalposition
    finallocstick78 - finalposition
    finallocstick79 - finalposition
    finallocstick80 - finalposition
    finallocstick81 - finalposition
    finallocstick82 - finalposition
    finallocstick83 - finalposition
    finallocstick84 - finalposition
    finallocstick85 - finalposition
    finallocstick86 - finalposition
    finallocstick87 - finalposition
    finallocstick88 - finalposition
    finloccube1 - finalposition
    finloccube2 - finalposition
    finloccube3 - finalposition
    finloccube4 - finalposition
    finloccube5 - finalposition
    finloccube6 - finalposition
    finloccube7 - finalposition
    finloccube8 - finalposition
    finloccube9 - finalposition
    finloccube10 - finalposition
    finloccube11 - finalposition
    finloccube12 - finalposition
    finloccube13 - finalposition
    finloccube14 - finalposition
    finloccube15 - finalposition
    finloccube16 - finalposition
    finloccube17 - finalposition
    finloccube18 - finalposition
  )
)
